# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jlong\Desktop\Evaluate the influence of hydrological conditions to constructed wetlands\ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 270, 561, 61))
        self.groupBox.setObjectName("groupBox")
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_27.setObjectName("label_27")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(300, 40, 21, 16))
        self.label_25.setObjectName("label_25")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(270, 20, 81, 16))
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_26.setObjectName("label_26")
        self.label11 = QtWidgets.QLabel(self.groupBox)
        self.label11.setGeometry(QtCore.QRect(110, 20, 151, 16))
        self.label11.setObjectName("label11")
        self.label13 = QtWidgets.QLabel(self.groupBox)
        self.label13.setGeometry(QtCore.QRect(110, 40, 151, 16))
        self.label13.setObjectName("label13")
        self.label12 = QtWidgets.QLabel(self.groupBox)
        self.label12.setGeometry(QtCore.QRect(380, 20, 181, 20))
        self.label12.setObjectName("label12")
        self.label14 = QtWidgets.QLabel(self.groupBox)
        self.label14.setGeometry(QtCore.QRect(380, 40, 171, 20))
        self.label14.setObjectName("label14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 340, 561, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label21 = QtWidgets.QLabel(self.groupBox_2)
        self.label21.setGeometry(QtCore.QRect(110, 10, 161, 16))
        self.label21.setObjectName("label21")
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(10, 10, 41, 16))
        self.label_34.setObjectName("label_34")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(300, 10, 51, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_38.setObjectName("label_38")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(300, 30, 41, 16))
        self.label_36.setObjectName("label_36")
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.label_39.setObjectName("label_39")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(300, 50, 61, 16))
        self.label_35.setObjectName("label_35")
        self.label23 = QtWidgets.QLabel(self.groupBox_2)
        self.label23.setGeometry(QtCore.QRect(110, 30, 161, 16))
        self.label23.setObjectName("label23")
        self.label25 = QtWidgets.QLabel(self.groupBox_2)
        self.label25.setGeometry(QtCore.QRect(110, 50, 161, 20))
        self.label25.setObjectName("label25")
        self.label22 = QtWidgets.QLabel(self.groupBox_2)
        self.label22.setGeometry(QtCore.QRect(380, 10, 171, 20))
        self.label22.setObjectName("label22")
        self.label24 = QtWidgets.QLabel(self.groupBox_2)
        self.label24.setGeometry(QtCore.QRect(380, 30, 181, 20))
        self.label24.setObjectName("label24")
        self.label26 = QtWidgets.QLabel(self.groupBox_2)
        self.label26.setGeometry(QtCore.QRect(380, 50, 171, 20))
        self.label26.setObjectName("label26")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 800, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 40, 81, 16))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 40, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 71, 21))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 31, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox_1 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_1.setGeometry(QtCore.QRect(50, 20, 201, 16))
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 71, 20))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_10.setGeometry(QtCore.QRect(870, 130, 151, 19))
        self.checkBox_10.setObjectName("checkBox_10")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 41, 16))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(170, 40, 81, 16))
        self.label_11.setObjectName("label_11")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(220, 40, 161, 16))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(90, 120, 41, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(170, 120, 51, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(260, 120, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(570, 120, 61, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(390, 120, 41, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(480, 120, 51, 16))
        self.label_17.setObjectName("label_17")
        self.spinBox_24 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_24.setGeometry(QtCore.QRect(430, 120, 31, 20))
        self.spinBox_24.setMaximum(2)
        self.spinBox_24.setObjectName("spinBox_24")
        self.spinBox_34 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_34.setGeometry(QtCore.QRect(420, 150, 31, 20))
        self.spinBox_34.setMaximum(2)
        self.spinBox_34.setObjectName("spinBox_34")
        self.spinBox_21 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_21.setGeometry(QtCore.QRect(130, 120, 31, 20))
        self.spinBox_21.setMaximum(2)
        self.spinBox_21.setObjectName("spinBox_21")
        self.spinBox_22 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_22.setGeometry(QtCore.QRect(220, 120, 31, 20))
        self.spinBox_22.setMaximum(2)
        self.spinBox_22.setObjectName("spinBox_22")
        self.spinBox_23 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_23.setGeometry(QtCore.QRect(340, 120, 31, 20))
        self.spinBox_23.setMaximum(2)
        self.spinBox_23.setObjectName("spinBox_23")
        self.spinBox_26 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_26.setGeometry(QtCore.QRect(630, 120, 31, 20))
        self.spinBox_26.setMaximum(2)
        self.spinBox_26.setObjectName("spinBox_26")
        self.spinBox_25 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_25.setGeometry(QtCore.QRect(530, 120, 31, 20))
        self.spinBox_25.setMaximum(2)
        self.spinBox_25.setObjectName("spinBox_25")
        self.spinBox_32 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_32.setGeometry(QtCore.QRect(250, 150, 31, 20))
        self.spinBox_32.setMaximum(2)
        self.spinBox_32.setObjectName("spinBox_32")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(100, 60, 54, 16))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(360, 60, 131, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_1.setGeometry(QtCore.QRect(150, 60, 111, 16))
        self.checkBox_1.setCheckable(True)
        self.checkBox_1.setChecked(False)
        self.checkBox_1.setTristate(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(260, 60, 101, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(60, 150, 51, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(390, 150, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(290, 150, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(160, 150, 91, 16))
        self.label_19.setObjectName("label_19")
        self.spinBox_31 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_31.setGeometry(QtCore.QRect(120, 150, 31, 20))
        self.spinBox_31.setMaximum(2)
        self.spinBox_31.setObjectName("spinBox_31")
        self.spinBox_33 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_33.setGeometry(QtCore.QRect(350, 150, 31, 20))
        self.spinBox_33.setMaximum(2)
        self.spinBox_33.setObjectName("spinBox_33")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(20, 90, 71, 21))
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(80, 90, 91, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(330, 90, 51, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(420, 90, 21, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(210, 90, 81, 16))
        self.label_23.setObjectName("label_23")
        self.spinBox_13 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_13.setGeometry(QtCore.QRect(380, 90, 31, 20))
        self.spinBox_13.setMaximum(1)
        self.spinBox_13.setObjectName("spinBox_13")
        self.spinBox_11 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_11.setGeometry(QtCore.QRect(170, 90, 31, 20))
        self.spinBox_11.setMaximum(1)
        self.spinBox_11.setObjectName("spinBox_11")
        self.spinBox_14 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_14.setGeometry(QtCore.QRect(440, 90, 31, 20))
        self.spinBox_14.setMaximum(1)
        self.spinBox_14.setObjectName("spinBox_14")
        self.spinBox_12 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_12.setGeometry(QtCore.QRect(290, 90, 31, 20))
        self.spinBox_12.setMaximum(1)
        self.spinBox_12.setObjectName("spinBox_12")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 20, 56, 17))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 420, 561, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_45 = QtWidgets.QLabel(self.groupBox_4)
        self.label_45.setGeometry(QtCore.QRect(270, 20, 91, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_4)
        self.label_46.setGeometry(QtCore.QRect(300, 40, 31, 16))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_4)
        self.label_47.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_4)
        self.label_48.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label_48.setObjectName("label_48")
        self.label31 = QtWidgets.QLabel(self.groupBox_4)
        self.label31.setGeometry(QtCore.QRect(100, 20, 161, 16))
        self.label31.setObjectName("label31")
        self.label33 = QtWidgets.QLabel(self.groupBox_4)
        self.label33.setGeometry(QtCore.QRect(100, 40, 161, 20))
        self.label33.setObjectName("label33")
        self.label32 = QtWidgets.QLabel(self.groupBox_4)
        self.label32.setGeometry(QtCore.QRect(380, 20, 161, 20))
        self.label32.setObjectName("label32")
        self.label34 = QtWidgets.QLabel(self.groupBox_4)
        self.label34.setGeometry(QtCore.QRect(380, 40, 161, 20))
        self.label34.setObjectName("label34")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(190, 220, 321, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 220, 161, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(530, 220, 51, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Possible change in hydraulic conditions"))
        self.label_27.setText(_translate("MainWindow", "Inflow loading rate"))
        self.label_25.setText(_translate("MainWindow", "HRT"))
        self.label_24.setText(_translate("MainWindow", "Flow fluctuation"))
        self.label_26.setText(_translate("MainWindow", "Water level"))
        self.label11.setText(_translate("MainWindow", "-"))
        self.label13.setText(_translate("MainWindow", "-"))
        self.label12.setText(_translate("MainWindow", "-"))
        self.label14.setText(_translate("MainWindow", "-"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Possible change in water quality"))
        self.label21.setText(_translate("MainWindow", "-"))
        self.label_34.setText(_translate("MainWindow", "DO"))
        self.label_37.setText(_translate("MainWindow", "BOD"))
        self.label_38.setText(_translate("MainWindow", "Nitrogen"))
        self.label_36.setText(_translate("MainWindow", "Phosphorus"))
        self.label_39.setText(_translate("MainWindow", "Pesticides"))
        self.label_35.setText(_translate("MainWindow", "Heavy metals"))
        self.label23.setText(_translate("MainWindow", "-"))
        self.label25.setText(_translate("MainWindow", "-"))
        self.label22.setText(_translate("MainWindow", "-"))
        self.label24.setText(_translate("MainWindow", "-"))
        self.label26.setText(_translate("MainWindow", "-"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Basic features of constructed wetlands"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1.Laboratory"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2.Small"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3.Large"))
        self.label.setText(_translate("MainWindow", "Scale:"))
        self.label_2.setText(_translate("MainWindow", "Inflow sources:"))
        self.label_3.setText(_translate("MainWindow", "Type:"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "1.Stormwater management"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "2.Municipal wastewater treatment"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "3.Agricultural pollutants removal"))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "4.Purification of natural water bodies"))
        self.comboBox_1.setItemText(4, _translate("MainWindow", "5.Mine drainage treatment"))
        self.comboBox_1.setItemText(5, _translate("MainWindow", "6.Ecosystem restoration"))
        self.comboBox_1.setItemText(6, _translate("MainWindow", "7.User-defined"))
        self.label_5.setText(_translate("MainWindow", "Water quality:"))
        self.checkBox_10.setText(_translate("MainWindow", "PPCPs"))
        self.label_6.setText(_translate("MainWindow", "Biology:"))
        self.label_11.setText(_translate("MainWindow", "Flow type"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1.Free water surface flow"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2.Horizontal subsurface flow"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "3.Vertical subsurface flow"))
        self.label_12.setText(_translate("MainWindow", "Nitrogen"))
        self.label_13.setText(_translate("MainWindow", "Phosphorus"))
        self.label_14.setText(_translate("MainWindow", "Suspended solids"))
        self.label_15.setText(_translate("MainWindow", "Heavy metals"))
        self.label_16.setText(_translate("MainWindow", "Organics"))
        self.label_17.setText(_translate("MainWindow", "Pesticides"))
        self.checkBox.setText(_translate("MainWindow", "Rainfall"))
        self.checkBox_3.setText(_translate("MainWindow", "Other natural water bodies"))
        self.checkBox_1.setText(_translate("MainWindow", "Domestic sewer system"))
        self.checkBox_2.setText(_translate("MainWindow", "Industary drainage"))
        self.label_7.setText(_translate("MainWindow", "Vegetations"))
        self.label_8.setText(_translate("MainWindow", "Birds"))
        self.label_9.setText(_translate("MainWindow", "Microorganism"))
        self.label_19.setText(_translate("MainWindow", "Fish and amphibians"))
        self.label_18.setText(_translate("MainWindow", "Hydraulic conditions"))
        self.label_20.setText(_translate("MainWindow", "Inflow loading rate"))
        self.label_21.setText(_translate("MainWindow", "Water level"))
        self.label_22.setText(_translate("MainWindow", "HRT"))
        self.label_23.setText(_translate("MainWindow", "Flow fluctuation"))
        self.pushButton_2.setText(_translate("MainWindow", "Apply"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Possible change in biology"))
        self.label_45.setText(_translate("MainWindow", "Fish and amphibians"))
        self.label_46.setText(_translate("MainWindow", "Birds"))
        self.label_47.setText(_translate("MainWindow", "Microorganism"))
        self.label_48.setText(_translate("MainWindow", "Vegetations"))
        self.label31.setText(_translate("MainWindow", "-"))
        self.label33.setText(_translate("MainWindow", "-"))
        self.label32.setText(_translate("MainWindow", "-"))
        self.label34.setText(_translate("MainWindow", "-"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1.Wet seasons"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2.Dry seasons"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "3.Prolonged flooding"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "4.Rainstrom"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "5.Highly fluctuating flow"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "6.Short-term inundation"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "7.Circular-flow corridor and baffled subsurface flow CWs"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "8.Tidal-operated CWs"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "9.Clogging of porous media"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "10.Artificial pulsing in subsurface CWs"))
        self.label_4.setText(_translate("MainWindow", "Changing hydrological conditions"))
        self.pushButton.setText(_translate("MainWindow", "Evaluate"))
